// <auto-generated />
namespace Example1_Store.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class iki : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(iki));
        
        string IMigrationMetadata.Id
        {
            get { return "202205280758191_iki"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
